# Docs:
# - https://github.com/lowlighter/metrics
# - https://github.com/lowlighter/metrics/blob/master/.github/readme/partials/documentation/setup/action.md
name: Metrics-CI
on:
  schedule: [{ cron: "12 0 * * *" }]
  workflow_dispatch:
  push:
    branches: ["master", "main"]
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          retries: 3
          retries_delay: 400
          retries_output_action: 2
          retries_delay_output_action: 120
          user: royerramirez
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Los_Angeles
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_topics_sort: starred
          plugin_topics_limit: 10